import Footer from "@/components/footer/footer";
import "./globals.css";
import { rubik } from "@/lib/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
